services:
  postgres_db:
    container_name: furnishart-db
    image: omerawan/furnishart-db:1.0
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: furnishart_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    container_name: furnishart-frontend
    image: omerawan/furnishart-frontend:1.0
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      BACKEND_API_URL: http://backend:3001/api
      NEXT_PUBLIC_BACKEND_API_URL: http://localhost:3001/api 
    depends_on:
      - backend
      
  backend:
    container_name: furnishart-backend
    image: omerawan/furnishart-backend:1.0
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres_db:5432/furnishart_db
      # DEV: "true"  # 👈 Add this line for development
    depends_on:
      - postgres_db
    
  asset-backend:
    container_name: furnishart-asset-backend
    image: omerawan/furnishart-assets:1.0
    restart: unless-stopped
    ports:
      - "3002:3002"
    
volumes:
  pgdata: